# 配置端口
server:
    port: 8082

# dubbo配置
spring:
    dubbo:
        application:
            # 应用名称
            name: dubbo-client
            # 注册中心地址 这里要填你自己zookeeper的地址
            registry: zookeeper://192.168.211.128:2181
        protocol:
            # 协议端口
            port: 20881